{% set version = "1.3.2" %}
{% set suitesparse_for_win_version = "5.7.2" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
    sha256: 3461fa42c1b2240ba4da1d985ca73503914157fc4c77417327ed6d7d85acdbe6

  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ suitesparse_for_win_version }}.tar.gz  # [win]
    sha256: fe3bc7c3bd1efdfa5cffffb5cebf021ff024c83b5daf0ab445429d3d741bd3ad  # [win]
    folder: suitesparse  # [win]
    patches:   # [win]
      - 0001-remove-BLAS_NO_UNDERSCORE-on-windows.patch                                                        # [win]

build:
  skip: true  # [py<35]
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - setuptools_scm
    - gsl
    - fftw
    - dsdp
    - glpk
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse          # [not win]
  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse          # [not win]

test:
  imports:
    - cvxopt
    - cvxopt.base
    - cvxopt.blas
    - cvxopt.cholmod
    - cvxopt.lapack
    - cvxopt.misc_solvers
    - cvxopt.umfpack
    - cvxopt.glpk
    - cvxopt.fftw
  source_files:
    - tests/*
    - examples/*
  commands:
    - pip list | grep cvxopt | grep {{ version }}
  requires:
    - pytest
    - pip

about:
  home: https://cvxopt.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Convex optimization package
  doc_url: https://cvxopt.org/userguide
  dev_url: https://github.com/cvxopt/cvxopt

extra:
  recipe-maintainers:
    - jakirkham
    - martinandersen
