{% set version = "1.1.9" %}

{% set variant = "openblas" %}


package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  sha256: 8f157e7397158812cabd340b68546f1baa55a486ed0aad8bc26877593dc2983d

build:
  skip: true  # [win]
  number: 202
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - gsl
    - fftw
    - glpk
    - suitesparse 4.5.4

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - gsl
    - fftw
    - glpk
    - suitesparse 4.5.4

test:
  imports:
    - cvxopt
  source_files:
    - tests/*.py
    - examples/*

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
