{% set version = "1.2.4" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  sha256: fa5ced96d71e4c3e6d50735e2ac4b8cf125c388cd77b1c5937febedb5f3a2fc1

build:
  skip: true  # [win and py<35]
  number: 200

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libblas
    - liblapack
    - python
    - setuptools
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse         # [not win]
    - suitesparse 5.1.*   # [win]

  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse         # [not win]
    - suitesparse 5.1.*   # [win]

test:
  imports:
    - cvxopt
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest

about:
  home: https://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package
  doc_url: https://cvxopt.org/userguide
  dev_url: https://github.com/cvxopt/cvxopt

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
