{% set version = "1.2.1" %}

{% set variant = "openblas" %}


package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  sha256: 12e3cfda982576b0b9b597d297aaf3172efa765a20fbed6f3c066aa0c48ee817

build:
  skip: true  # [win and py<35]
  number: 1200
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse 4.5.6|4.5.6.*   # [not win]
    - suitesparse 5.1.*   # [win]

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse 4.5.6|4.5.6.*   # [not win]
    - suitesparse 5.1.*   # [win]

test:
  imports:
    - cvxopt
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
