{% set version = "1.1.9" %}

{% set variant = "openblas" %}


package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  md5: a56e7b23d76c2b5aaf3bea2a7c245ea7

build:
  skip: true  # [win]
  number: 0
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - gsl
    - fftw
    - glpk
    - suitesparse 4.4.*

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - gsl
    - fftw
    - glpk

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GPL 3
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
