{% set version = "1.2.0" %}

{% set variant = "openblas" %}


package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  sha256: 3296c9d49b7dcb894b20db5d7d1c1a443912b4d82358e03f836575e8398e0d60
  patches: cvxopt_win_patch.diff   # [win]

build:
  skip: true  # [win and py<35]
  number: 201
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas
    - gsl
    - fftw
    - dsdp   # [not win]
    - glpk
    - suitesparse 4.5.6|4.5.6.*   # [not win]
    - suitesparse 5.1.*   # [win]

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - gsl
    - fftw
    - dsdp   # [not win]
    - glpk
    - suitesparse 4.5.6|4.5.6.*   # [not win]
    - suitesparse 5.1.*   # [win]

test:
  imports:
    - cvxopt
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
