appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QimLQPycjUrH0EwUR2jF4yK3TWDIRdYSwo6EUyvDl7dCkFMG9iKXlWxkJ54muctuXUMRIRBlFeqxSpbAe11axyX+c7d0T1doAVcuqR0gcQx6MO4r0wuPML8/uqAch9MmvqUrGb8+EKu79ED00+vdE8uZU8RiM/mY5uONuTld6jsoyloGId3TMSIfobF3vBNbzC7r8qE4gIkBaa2nVBXeY4pf9XtPL0N0msN+cgzSfbufXHx0tJB/e9l/WKkNDWT70tGpVlt+mKH/qPp0bgu+NdDq3gG0oECGy+hN8fUrKnhLuUuCPZy7svlYQhQPQDEoFCV3oNcdoeBV6HoJmCYmwpYZWcEkqHGDCCOls4qJQr1zsU69zVmsMh5U1I82UOE++UiUD4WaSiSkbEPQaZp45pClWxs17B1KNWaqi6+cevuGzXoITJ3aA1cNRS/T7s/yIE7HZBOqamgt7ztN+n93naWJHNUtK+44fwTKv38F7yguhS/Yh3ZiCwSWlbxflI9G/nU8PBT1x6LppjVMnBGgWe48GGEEjtP7U/ruJNmPSWEZuGnHSdeENocwPhGSy2fGcgDM1rdk6wU+M66U8iPGPUkOPByWPkvwR/lBdU4XMOfhg3MenVaF1HOhMbRyzPfbu0enT1ugx8TsfIFbMYXbFdZQ7Gq1Dx9BDW0sE2n2Omc=}
provider:
  win: azure
